{% set name = "ormar" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ormar-{{ version }}.tar.gz
  sha256: e9b05fa7cc6cc540470425c98646ba97f0cd90f4030ab626eed5b1356f25778e

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8.0,<4.0.0
  run:
    - python >=3.8.0,<4.0.0
    - databases >=0.7.0,<0.8.0
    - pydantic >=2.5.3,<3.0.0
    - sqlalchemy >=1.4.42,<2.0.0

test:
  imports:
    - ormar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/collerek/ormar
  summary: A simple async ORM with fastapi in mind and pydantic validation.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://collerek.github.io/ormar/
  description: |
    The ormar package is an async mini ORM for Python, with support for
     Postgres, MySQL, and SQLite. The main benefit of using ormar includes the
     ability to get an async ORM that can be used with async frameworks
     (fastapi, starlette etc.). Using ormar would simplly workflow with just one
     model to maintain—you don't have to maintain pydantic and other orm model
     (sqlalchemy, peewee, gino etc.)

extra:
  recipe-maintainers:
    - thewchan
